### ISSUE TITLE
Textmate grammar provider scope collision when mixed with @theia/json

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-plantuml-extension#15]
I noticed the following exception when starting a Theia application that includes `@theia/plantuml` and `@theia/json` :

```
root WARN Error: a registered grammar provider for 'source.json' scope is overridden
    at e.registerTextmateGrammarScope (http://localhost:3003/bundle.js:19:422576)
    at e.registerTextmateLanguage (http://localhost:3003/bundle.js:117:1008834)
    at e.initialize (http://localhost:3003/bundle.js:30:501976)
    at e.<anonymous> (http://localhost:3003/bundle.js:12:365064)
    at http://localhost:3003/bundle.js:12:360054
    at Object.next (http://localhost:3003/bundle.js:12:360159)
    at http://localhost:3003/bundle.js:12:359072
    at new Promise (<anonymous>)
    at a (http://localhost:3003/bundle.js:12:358849)
    at e.startContributions (http://localhost:3003/bundle.js:12:364835)

```

It seems that the collision is due to the reuse of the same scope id/key: `source.json`: 
https://github.com/theia-ide/theia-plantuml-extension/blob/master/plantuml/src/browser/plantuml-grammar-contribution.ts#L58

I guess this should rather be something like ~`source.plantuml`?~ update: actually `source.wsd` is used in the grammar file. 

Note: since `@theia/debug` depends on `@theia/json`, the problem can happen even if the later is not included directly.

**Comment by marcdumais-work** [comment]
Maybe obvious, but with this problem, the textmate colloring does not work with `.plantuml` files and their aliases.
